# Reconstructed by StackSnap from running containers.
# This is a best-effort snapshot — review before use.
services:
  ntfy:
    image: binwiederhier/ntfy:latest
    restart: unless-stopped
    ports:
      - "2586:80"
      - ":::2586:80"
    volumes:
      - "/mnt/nvme/docker/ntfy/cache:/var/cache/ntfy:rw"
      - "/mnt/nvme/docker/ntfy/data:/var/lib/ntfy:rw"
    environment:
      NTFY_AUTH_FILE: "/var/lib/ntfy/auth.db"
      NTFY_AUTH_DEFAULT_ACCESS: "read-write"
      NTFY_BEHIND_PROXY: "true"
      NTFY_BASE_URL: "http://192.168.1.39:2586"
      NTFY_LISTEN_HTTP: ":80"
      NTFY_CACHE_FILE: "/var/cache/ntfy/cache.db"
