version: "3.8"

# ========================
# TEMPLATES
# ========================

x-common-env: &common-env
  TZ: Europe/London
  PUID: 1000
  PGID: 1000

x-security: &security
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

x-watchtower: &watchtower
  labels:
    - com.centurylinklabs.watchtower.enable=true

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"


# =========================================================
# SERVICES
# =========================================================
services:

# =========================================================
# JELLYFIN
# =========================================================

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: "1000:1000"
    ports: 
       
      - 8096:8096

    devices:
      - /dev/dri:/dev/dri

    group_add:
      - "44"
      - "993"

    environment:
      <<: *common-env
      LIBVA_DRIVER_NAME: iHD

    volumes:
      - /mnt/nvme/docker/jellyfin/config:/config
      - /mnt/nvme/docker/jellyfin/cache:/cache
      - /mnt/nas/data/media:/media

    networks:
      - traefik_traefik
      - ichor

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_traefik
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.mortalsrv.uk`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.tls.certresolver=letsencrypt
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

  # 👇 ADD THESE TWO
      - traefik.http.middlewares.jellyfin-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.jellyfin.middlewares=jellyfin-headers
  
    <<: [*security, *watchtower, *logging]


# =========================================================
# JELLYSEERR
# =========================================================

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    user: "1000:1000"

    environment:
      <<: *common-env

    volumes:
      - /mnt/nvme/docker/jellyseerr:/app/config

    networks:
      - traefik_traefik
      - ichor

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_traefik
      - traefik.http.routers.jellyseerr.rule=Host(`jellyseer.mortalsrv.uk`)
      - traefik.http.routers.jellyseerr.entrypoints=websecure
      - traefik.http.routers.jellyseerr.tls.certresolver=letsencrypt
      - traefik.http.services.jellyseerr.loadbalancer.server.port=5055

    <<: [*security, *watchtower, *logging]


# =========================================================
# POSTER UPDATER (internal only)
# =========================================================

  jellyfinupdateposter:
    image: iceshadow/jellyfinupdateposter:latest
    container_name: jellyfinupdateposter

    environment:
      TZ: Europe/London
      JELLYFIN_URL: http://jellyfin:8096   # <- internal docker DNS (better)
      JELLYFIN_API_KEY: d53e311cf1e74b339a1d4ec2e19767b9
      TMDB_API_KEY: f88feb1409d53e70bac639a08b92e5ae


    volumes:
      - /mnt/nvme/docker/jellyfin-update-poster:/mount

    networks:
      - ichor

    command: "--force"

    <<: [*security, *watchtower, *logging]


# =========================================================
# NETWORKS
# =========================================================

networks:
  traefik_traefik:
    external: true

  ichor:
    external: true
