version: "3.9"

services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy

    restart: unless-stopped

    ports:
      - 5000:8080

    environment:
      - NODE_ENV=production
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London

    volumes:
      - /mnt/nvme/docker/dashy/conf.yml:/app/public/conf.yml
      - /mnt/nvme/docker/dashy/data:/app/data