version: "3.9"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    user: 1000:1000
    environment:
      ROCKET_ENV: production
      ROCKET_PORT: 8080
      ROCKET_WORKERS: 10
      SIGNUPS_ALLOWED: TRUE
      ADMIN_TOKEN: '$$argon2id$$v=19$$m=65540,t=3,p=4$$UEcxLEDGq1c1qplWVV+6CIYTIRpkIE6dRXAsBzdGDCk$$Vl0Qn4/05RhPhe++lJhkkC29kjMxHPWNN+XnrhawT04'
      ROCKET_SITE: "https://vault.mortalsrv.uk"
    volumes:
      - /mnt/nvme/docker/vaultwarden:/data
    networks:
      - traefik_traefik
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vault.mortalsrv.uk`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt"

      - "traefik.http.services.vaultwarden.loadbalancer.server.port=8080"
      - "traefik.http.routers.vaultwarden.middlewares=vaultwarden-strip"
      - "traefik.http.middlewares.vaultwarden-strip.stripprefix.prefixes=/vw_static"

      - "com.centurylinklabs.watchtower.enable=true"


networks:
  traefik_traefik:
    external: true
