# Reconstructed by StackSnap from running containers.
# This is a best-effort snapshot — review before use.
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    restart: unless-stopped
    ports:
      - "21027:21027"
      - "22000:22000"
      - "22000:22000"
      - "8384:8384"
      - ":::21027:21027"
      - ":::22000:22000"
      - ":::22000:22000"
      - ":::8384:8384"
    volumes:
      - "/mnt/nvme/docker/syncthing/config:/config:rw"
      - "/mnt/mas/data:/data:rw"
    environment:
      TZ: "Europe/London"
      PUID: "1000"
      PGID: "1000"
      PS1: "$(whoami)@$(hostname):$(pwd)\$ "
      S6_CMD_WAIT_FOR_SERVICES_MAXTIME: "0"
      S6_VERBOSITY: "1"
      S6_STAGE2_HOOK: "/docker-mods"
      VIRTUAL_ENV: "/lsiopy"
      LSIO_FIRST_PARTY: "true"
