version: "3.8"

services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    restart: unless-stopped

    ports:
      - 8070:80

    volumes:
      - /mnt/nvme/docker/gotify:/app/data

    networks:
      - ichor

networks:
  ichor:
    external: true
