version: "3.8"

services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    restart: unless-stopped
    environment:
      - PUID=1000           # your UID
      - PGID=1000           # your GID
      - TZ=Europe/London
      # Optional:
      # - PASSWORD=          # protect settings page
      # - MODE=standalone    # store results locally
      # - TELEMETRY=true     # keep history of tests
    volumes:
      - /mnt/nvme/docker/librespeed:/config
    ports:
      - 8082:80             # access via http://<tailscale-ip>:8080
