version: "3.8"

services:
  nzbget:
    image: nzbgetcom/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - NZBGET_USER=moneybanks77
      - NZBGET_PASS=Mason180n!$
    volumes:
      - /mnt/nas/data/usenet:/data/usenet
      - /mnt/nvme/docker/nzbget:/config
    ports:
      - 6789:6789
    networks:
      - ichor
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  ichor:
    external: true