version: "3.8"

# ========================
# TEMPLATES
# ========================

x-security: &security
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

x-watchtower: &watchtower
  labels:
    - com.centurylinklabs.watchtower.enable=true

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"


# =========================================================
# SERVICES
# =========================================================
services:

# =========================================================
# EDGE GATEWAY (TRAEFIK)
# =========================================================

  traefik:
    image: traefik:latest
    container_name: traefik


    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik_traefik

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.forwardedHeaders.trustedIPs=172.16.0.0/12
      - --api.dashboard=true
      - --api.insecure=true
      - --ping=true

      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=moneybanks77@proton.me
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json

      - --log.level=INFO
      - --accesslog=true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/nvme/docker/traefik/acme.json:/acme.json
      - /mnt/nvme/docker/traefik/logs:/logs


    networks:
      - traefik_traefik
   
    healthcheck:
        test: ["CMD", "wget", "-qO-", "http://localhost:8080/ping"]
        interval: 30s
        timeout: 5s
        retries: 3


    <<: [*security, *watchtower, *logging]


# =========================================================
# CROWDSEC ENGINE
# =========================================================

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec

    environment:
      TZ: Europe/London
      COLLECTIONS: crowdsecurity/traefik

    volumes:
      - /mnt/nvme/docker/crowdsec/config:/etc/crowdsec
      - /mnt/nvme/docker/crowdsec/data:/var/lib/crowdsec/data
      - /mnt/nvme/docker/traefik/logs:/logs:ro

    networks:
      - traefik_traefik

    <<: [*security, *watchtower, *logging]


# =========================================================
# CROWDSEC BOUNCER
# =========================================================

  traefik-bouncer:
    image: fbonalair/traefik-crowdsec-bouncer:latest
    container_name: traefik-bouncer

    environment:
      CROWDSEC_AGENT_HOST: crowdsec:8080
      CROWDSEC_BOUNCER_API_KEY: CHANGE_ME
      LOG_LEVEL: warn

    depends_on:
      - crowdsec

    networks:
      - traefik_traefik

    <<: [*security, *watchtower, *logging]


# =========================================================
# AUTHELIA
# =========================================================

  authelia:
    image: authelia/authelia:latest
    container_name: authelia

    volumes:
      - /mnt/nvme/docker/authelia/config:/config

    networks:
      - traefik_traefik

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_traefik
      - traefik.http.routers.authelia.rule=Host(`auth.mortalsrv.uk`)
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.tls.certresolver=letsencrypt
      - traefik.http.services.authelia.loadbalancer.server.port=9091

    <<: [*security, *watchtower, *logging]


# =========================================================
# NETWORKS
# =========================================================

networks:
  traefik_traefik:
    external: true
  ichor:
    external: true
    