# Reconstructed by StackSnap from running containers.
# This is a best-effort snapshot — review before use.
services:
  ownfoil:
    image: a1ex4/ownfoil
    restart: unless-stopped
    ports:
      - "8465:8465"
      - ":::8465:8465"
    volumes:
      - "/mnt/nvme/docker/ownfoil/config:/app/config:rw"
      - "/mnt/nas/data/torrents/switch:/games:rw"
    environment:
      PYTHON_VERSION: "3.14.3"
      PYTHON_SHA256: "a97d5549e9ad81fe17159ed02c68774ad5d266c72f8d9a0b5a9c371fe85d902b"
