version: "3.8"

services:

# ========================
# GLUETUN (VPN CORE)
# ========================
  gluetun:
    image: qmcgaw/gluetun:v3.40.1
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

    ports:
      - 8090:8090   # qbit UI only

    volumes:
      - /mnt/nvme/docker/gluetun:/gluetun
      - /mnt/nvme/docker/scripts:/scripts

    environment:
      - TZ=Europe/London

      # ===== Proton =====
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=CAO1TzzCceE5R/BlybttZeFLYpESy87XFERR+f3HGls=
      - SERVER_COUNTRIES=Netherlands

      # ===== Port forwarding =====
      - VPN_PORT_FORWARDING=on
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/scripts/update_qb_port.sh

      # ===== LAN access =====
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24,172.19.0.0/16,172.20.0.0/16,172.22.0.0/16

    restart: unless-stopped

# ========================
# qBittorrent (INSIDE VPN)
# ========================
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun

    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8090

    volumes:
      - /mnt/nvme/docker/qbittorrent:/config
      - /mnt/nas/data/torrents:/data/torrents

    depends_on:
      - gluetun

    restart: unless-stopped

# ========================
# FlareSolverr (OUTSIDE VPN)
# ========================
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=Europe/London
    ports:
      - 8191:8191
    networks:
      - ichor
    restart: unless-stopped

# ========================
# Prowlarr (OUTSIDE VPN)
# ========================
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/nvme/docker/prowlarr:/config
    ports:
      - 9696:9696
    networks:
      - ichor
    restart: unless-stopped

# ========================
# cross-seed (OUTSIDE VPN)
# ========================
  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:latest
    container_name: cross-seed
    user: 1000:1000
    command: daemon

    volumes:
      - /mnt/nvme/docker/cross-seed:/config
      - /mnt/nvme/docker/cross-seed/cross-seeds:/cross-seeds
      - /mnt/nas/data:/data

    ports:
      - 2468:2468

    networks:
      - ichor

    restart: unless-stopped

# ========================
# NETWORKS
# ========================
networks:
  ichor:
    external: true
