version: "3.8"

services:
  linkwarden-db:
    image: postgres:16-alpine
    container_name: linkwarden-db
    environment:
      POSTGRES_DB: linkwarden
      POSTGRES_USER: linkwardenuser
      POSTGRES_PASSWORD: "Mason180l!$"
    volumes:
      - /mnt/nvme/docker/linkwarden/db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ichor
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U linkwardenuser -d linkwarden"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: linkwarden
    environment:
      DATABASE_URL: postgres://linkwardenuser:Mason180l!$@linkwarden-db:5432/linkwarden
      NEXTAUTH_SECRET: "KbzxEDEC0Ou6hmQy6TXCJAKTeFLOiHe7Sirvl1Ld0dYVuzDQykT1A0lSvp42goEM"
      NEXTAUTH_URL: "https://link.mortalsrv.uk"
      NEXT_PUBLIC_DISABLE_REGISTRATION: "false"
    # ❌ Remove this, it's breaking the container
    # volumes:
    #   - /mnt/nvme/docker/linkwarden/data:/data
    depends_on:
      - linkwarden-db
    restart: unless-stopped
    ports:
      - 3020:3000
    networks:
      - ichor
      - traefik_traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkwarden.rule=Host(`link.mortalsrv.uk`)"
      - "traefik.http.routers.linkwarden.entrypoints=websecure"
      - "traefik.http.routers.linkwarden.tls.certresolver=letsencrypt"
      - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  ichor:
    external: true
  traefik_traefik:
    external: true



