# Reconstructed by StackSnap from running containers.
# This is a best-effort snapshot — review before use.
services:
  wizarr:
    image: ghcr.io/wizarrrr/wizarr:latest
    restart: unless-stopped
    ports:
      - "8081:5690"
      - ":::8081:5690"
    volumes:
      - "/mnt/nvme/docker/wizarr:/data:rw"
    environment:
      WIZARR_JELLYFIN_API_KEY: "14ca69c0a8724b4c9bbcd45660295b8b"
      TZ: "Europe/London"
      WIZARR_JELLYFIN_URL: "https://jellyfin.mortalsrv.uk"
      GPG_KEY: "7169605F62C751356D054A26A821E680E5FA6305"
      PYTHON_VERSION: "3.13.10"
      PYTHON_SHA256: "bc673c04375a1a3f0808c27ba8f0411ab811ad390a8740318ccb9c60fad8fd77"
      UV_TOOL_BIN_DIR: "/usr/local/bin"
      PUID: "1000"
      PGID: "1000"
      APP_VERSION: "v2025.12.0"
      FLASK_ENV: "production"
