services:
  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
  huntarr:
    image: huntarr/huntarr:latest
  lazylibrarian:
    image: linuxserver/lazylibrarian:latest
  bazarr:
    image: linuxserver/bazarr:latest
  suggestarr:
    image: ciuse99/suggestarr:latest
  tracearr:
    image: ghcr.io/connorgallopo/tracearr:supervised
  lidarr:
    image: linuxserver/lidarr:latest
  whisparr:
    image: ghcr.io/thespad/whisparr:latest
  autobrr:
    image: ghcr.io/autobrr/autobrr:latest
  radarr:
    image: linuxserver/radarr:latest
  sonarr:
    image: linuxserver/sonarr:latest
  unpackerr:
    image: golift/unpackerr
  sportarr:
    image: sportarr/sportarr:latest
  audiobookshelf:
    image: advplyr/audiobookshelf:latest
