# Reconstructed by StackSnap from running containers.
# This is a best-effort snapshot — review before use.
services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    restart: unless-stopped
    ports:
      - "3020:3000"
      - ":::3020:3000"
    environment:
      NEXT_PUBLIC_DISABLE_REGISTRATION: "false"
      DATABASE_URL: "postgres://linkwardenuser:Mason180l!$@linkwarden-db:5432/linkwarden"
      NEXTAUTH_SECRET: "KbzxEDEC0Ou6hmQy6TXCJAKTeFLOiHe7Sirvl1Ld0dYVuzDQykT1A0lSvp42goEM"
      NEXTAUTH_URL: "https://link.mortalsrv.uk"
      NODE_VERSION: "20.19.6"
      YARN_VERSION: "1.22.22"
      YARN_HTTP_TIMEOUT: "10000000"
      COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
      PRISMA_HIDE_UPDATE_MESSAGE: "1"
  linkwarden-db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - "/mnt/nvme/docker/linkwarden/db:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_PASSWORD: "Mason180l!$"
      POSTGRES_DB: "linkwarden"
      POSTGRES_USER: "linkwardenuser"
      GOSU_VERSION: "1.19"
      PG_MAJOR: "16"
      PG_VERSION: "16.11"
      PG_SHA256: "6deb08c23d03d77d8f8bd1c14049eeef64aef8968fd8891df2dfc0b42f178eac"
      DOCKER_PG_LLVM_DEPS: "llvm19-dev 		clang19"
      PGDATA: "/var/lib/postgresql/data"
