# Reconstructed by StackSnap from running containers.
# This is a best-effort snapshot — review before use.
services:
  smartarr-backend:
    image: smartarr-smartarr-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
      - ":::8001:8001"
    volumes:
      - "/mnt/nvme/docker/smartarr/db:/app/data:rw"
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      NTFY_URL: "http://ntfy:80"
      DISCORD_WEBHOOK_URL: ""
      JELLYFIN_EXTERNAL_URL: "https://jellyfin.mortalsrv.uk"
      STORAGE_POLL_INTERVAL: "300"
      PROWLARR_URL: "http://prowlarr:9696"
      DISK_WARNING_THRESHOLD: "80"
      SABNZBD_URL: "http://sabnzbd:8080"
      LIDARR_API_KEY: ""
      QBITTORRENT_URL: "http://192.168.1.39:8090"
      TEMP_WARNING_CELSIUS: "75"
      CPU_THROTTLE_THRESHOLD: "80"
      NTFY_TOPIC: "smartarr"
      BAZARR_API_KEY: ""
      SONARR_URL: "http://sonarr:8989"
      NETWORK_POLL_INTERVAL: "30"
      PORT: "8001"
      SYSTEM_POLL_INTERVAL: "10"
      RADARR_API_KEY: "6a41a223db9f4c67ba14e96d4e269f87"
      IDLE_HOURS_TO_FLAG: "90"
      ARR_POLL_INTERVAL: "60"
      SABNZBD_API_KEY: "143bf890a4674c86a0467b8f19b0e7d8"
      LIDARR_URL: "http://lidarr:8686"
      JELLYFIN_API_KEY: "fd6091db381f4e83ab4ec2e53cc40eb8"
      JELLYFIN_URL: "http://jellyfin:8096"
      GOTIFY_TOKEN: ""
      SONARR_API_KEY: "e316584e1fcd42409f8f34c49c1f6f56"
      JELLYSEERR_API_KEY: ""
      OLLAMA_URL: "http://ollama:11434"
      OLLAMA_MODEL: "mistral"
      RADARR_4K_API_KEY: "5695b81a4e534a898f32038c83a364a4"
      DATABASE_URL: "sqlite+aiosqlite:////app/data/smartarr.db"
      RADARR_4K_URL: "http://192.168.1.39:3021"
      QBITTORRENT_USER: "admin"
      PROWLARR_API_KEY: "4e3b75fb49fb4dffb17cab31678dec36"
      JELLYSEERR_URL: ""
      RAM_THROTTLE_THRESHOLD: "85"
      QBITTORRENT_PASS: "Mason180q"
      NTFY_TOKEN: "tk_7urhllc6ap2z5tmcd74yq8tqqiaqh"
      BAZARR_URL: ""
      DISK_CRITICAL_THRESHOLD: "92"
      RADARR_URL: "http://192.168.1.39:3001"
      GOTIFY_URL: ""
      GPG_KEY: "7169605F62C751356D054A26A821E680E5FA6305"
      PYTHON_VERSION: "3.12.12"
      PYTHON_SHA256: "fb85a13414b028c49ba18bbd523c2d055a30b56b18b92ce454ea2c51edc656c4"
  smartarr-frontend:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8083:80"
      - ":::8083:80"
    volumes:
      - "/mnt/nvme/docker/smartarr/frontend:/usr/share/nginx/html:ro"
      - "/mnt/nvme/docker/smartarr/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    environment:
      NGINX_VERSION: "1.29.5"
      PKG_RELEASE: "1"
      DYNPKG_RELEASE: "1"
      NJS_VERSION: "0.9.5"
      NJS_RELEASE: "1"
      ACME_VERSION: "0.3.1"
