# Reconstructed by StackSnap from running containers.
# This is a best-effort snapshot — review before use.
services:
  standardnotes:
    image: standardnotes/server:latest
    restart: unless-stopped
    volumes:
      - "/mnt/nvme/docker/standardnotes/uploads:/opt/server/packages/files/dist/uploads:rw"
      - "/mnt/nvme/docker/standardnotes/logs:/var/lib/server/logs:rw"
    environment:
      NODE_ENV: "production"
      DB_TYPE: "postgres"
      DB_HOST: "standardnotes_db"
      DB_PORT: "5432"
      DB_DATABASE: "standardnotes"
      DB_USERNAME: "snuser"
      DB_PASSWORD: "CHANGE_ME"
      NODE_VERSION: "20.10.0"
      YARN_VERSION: "1.22.19"
  standardnotes_db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - "/mnt/nvme/docker/standardnotes/postgres:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_USER: "snuser"
      POSTGRES_PASSWORD: "CHANGE_ME_STRONG_PASSWORD"
      POSTGRES_DB: "standardnotes"
      GOSU_VERSION: "1.19"
      PG_MAJOR: "16"
      PG_VERSION: "16.11"
      PG_SHA256: "6deb08c23d03d77d8f8bd1c14049eeef64aef8968fd8891df2dfc0b42f178eac"
      DOCKER_PG_LLVM_DEPS: "llvm19-dev 		clang19"
      PGDATA: "/var/lib/postgresql/data"
  standardnotes_localstack:
    image: localstack/localstack:latest
    restart: unless-stopped
    environment:
      SERVICES: "sns,sqs"
      GPG_KEY: "7169605F62C751356D054A26A821E680E5FA6305"
      PYTHON_VERSION: "3.13.11"
      PYTHON_SHA256: "16ede7bb7cdbfa895d11b0642fa0e523f291e6487194d53cf6d3b338c3a17ea2"
      USER: "localstack"
      PYTHONUNBUFFERED: "1"
      LOCALSTACK_BUILD_DATE: "2026-02-06"
      LOCALSTACK_BUILD_GIT_HASH: "20cc1b384"
      LOCALSTACK_BUILD_VERSION: "4.13.2.dev34"
  standardnotes_redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - "/mnt/nvme/docker/standardnotes/redis:/data:rw"
    environment:
      GOSU_VERSION: "1.17"
      REDIS_VERSION: "7.4.7"
      REDIS_DOWNLOAD_URL: "http://download.redis.io/releases/redis-7.4.7.tar.gz"
      REDIS_DOWNLOAD_SHA: "c97e57b0df330a9e091cacff012bebe763c275398cf36ff44cdba876814b595b"
  standardnotes_web:
    image: standardnotes/web:latest
    restart: unless-stopped
    ports:
      - "3050:80"
      - ":::3050:80"
    environment:
      API_SERVER_URL: "http://mortalsrv.li-fir.ts.net:3050"
      NGINX_VERSION: "1.29.5"
      PKG_RELEASE: "1"
      DYNPKG_RELEASE: "1"
      NJS_VERSION: "0.9.5"
      NJS_RELEASE: "1"
      ACME_VERSION: "0.3.1"
